// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iexsamuudfbozyihmyiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlleHNhbXV1ZGZib3p5aWhteWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjk0NzMsImV4cCI6MjA3MTc0NTQ3M30.us53bZoC5BFfGp-uEzjm7TinNX-c21HnNK6uFI7YhoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});